// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Watchly.Infrastructure.DbContexts;

#nullable disable

namespace Watchly.Infrastructure.Migrations
{
    [DbContext(typeof(WatchlyDbContext))]
    [Migration("20260405161535_AddTvShows")]
    partial class AddTvShows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer")
                        .HasColumnName("episode_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("text");

                    b.Property<int?>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("EpisodeId")
                        .HasDatabaseName("ix_comments_episode_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_comments_title_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal_number");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("poster_url");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<int>("Runtime")
                        .HasColumnType("integer")
                        .HasColumnName("runtime");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_episodes");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_episodes_season_id");

                    b.ToTable("episodes");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_keywords");

                    b.ToTable("keywords");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.KeywordTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTvShow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tv_show");

                    b.Property<int>("KeywordId")
                        .HasColumnType("integer")
                        .HasColumnName("keyword_id");

                    b.Property<int>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.HasKey("Id")
                        .HasName("pk_keyword_titles");

                    b.HasIndex("KeywordId")
                        .HasDatabaseName("ix_keyword_titles_keyword_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_keyword_titles_title_id");

                    b.ToTable("keyword_titles");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.ProductionCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_production_company");

                    b.ToTable("production_company");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal_number");

                    b.Property<int>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_seasons_title_id");

                    b.ToTable("seasons");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.SpokenLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_spoken_languages");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("spoken_languages");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Actors")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("actors");

                    b.Property<float?>("AvgTmdbRating")
                        .HasColumnType("real")
                        .HasColumnName("avg_tmdb_rating");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer")
                        .HasColumnName("content_type");

                    b.Property<string>("Director")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("director");

                    b.Property<string>("HomePage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("home_page");

                    b.Property<bool>("IsAdult")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adult");

                    b.Property<string>("LocalizationLanguages")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("localization_languages");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("overview");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("poster_url");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<int>("Runtime")
                        .HasColumnType("integer")
                        .HasColumnName("runtime");

                    b.Property<string>("Tagline")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tagline");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_titles");

                    b.ToTable("titles");

                    b.HasDiscriminator<int>("ContentType").HasValue(1);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Watchly.Domain.Entities.TitleGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<bool>("IsTvShow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tv_show");

                    b.Property<int>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.HasKey("Id")
                        .HasName("pk_title_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_title_genres_genre_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_title_genres_title_id");

                    b.ToTable("title_genres");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.TitleProductionCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTvShow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tv_show");

                    b.Property<int>("ProductionCompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("production_company_id");

                    b.Property<int>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.HasKey("Id")
                        .HasName("pk_title_production_companies");

                    b.HasIndex("ProductionCompanyId")
                        .HasDatabaseName("ix_title_production_companies_production_company_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_title_production_companies_title_id");

                    b.ToTable("title_production_companies");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.TitleSpokenLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTvShow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tv_show");

                    b.Property<int>("SpokenLanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("spoken_language_id");

                    b.Property<int>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.HasKey("Id")
                        .HasName("pk_title_spoken_languages");

                    b.HasIndex("SpokenLanguageId")
                        .HasDatabaseName("ix_title_spoken_languages_spoken_language_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_title_spoken_languages_title_id");

                    b.ToTable("title_spoken_languages");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Watchly.Domain.Entities.UserContentActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer")
                        .HasColumnName("activity_type");

                    b.Property<int>("ContentId")
                        .HasColumnType("integer")
                        .HasColumnName("content_id");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watched_at");

                    b.HasKey("Id")
                        .HasName("pk_user_content_activities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_content_activities_user_id");

                    b.ToTable("user_content_activities");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.UserTitleProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_title_progresses");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_user_title_progresses_title_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_title_progresses_user_id");

                    b.ToTable("user_title_progresses");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer")
                        .HasColumnName("episode_id");

                    b.Property<int?>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_votes");

                    b.HasIndex("EpisodeId")
                        .HasDatabaseName("ix_votes_episode_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_votes_title_id");

                    b.HasIndex("UserId");

                    b.ToTable("votes");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.WatchList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_watch_lists");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_watch_lists_user_id");

                    b.ToTable("watch_lists");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.WatchListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TitleId")
                        .HasColumnType("integer")
                        .HasColumnName("title_id");

                    b.Property<int>("WatchListId")
                        .HasColumnType("integer")
                        .HasColumnName("watch_list_id");

                    b.HasKey("Id")
                        .HasName("pk_watch_list_items");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_watch_list_items_title_id");

                    b.HasIndex("WatchListId")
                        .HasDatabaseName("ix_watch_list_items_watch_list_id");

                    b.ToTable("watch_list_items");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.TvShow", b =>
                {
                    b.HasBaseType("Watchly.Domain.Entities.Title");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("created_by");

                    b.Property<int?>("EpisodeRunTime")
                        .HasColumnType("integer")
                        .HasColumnName("episode_run_time");

                    b.Property<DateTime?>("FirstAirDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_air_date");

                    b.Property<bool>("InProduction")
                        .HasColumnType("boolean")
                        .HasColumnName("in_production");

                    b.Property<DateTime?>("LastAirDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_air_date");

                    b.Property<int>("NumberOfEpisodes")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_episodes");

                    b.Property<int>("NumberOfSeasons")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_seasons");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("original_language");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("original_name");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<float?>("VoteAverage")
                        .HasColumnType("real")
                        .HasColumnName("vote_average");

                    b.ToTable("titles");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Watchly.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.Episode", "Episode")
                        .WithMany("Comments")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_comments_episodes_episode_id");

                    b.HasOne("Watchly.Domain.Entities.Title", "Title")
                        .WithMany("Comments")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_comments_titles_title_id");

                    b.HasOne("Watchly.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_asp_net_users_user_id");

                    b.Navigation("Episode");

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Episode", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_seasons_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.KeywordTitle", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.Keyword", "Keyword")
                        .WithMany("KeywordTitles")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_keyword_titles_keywords_keyword_id");

                    b.HasOne("Watchly.Domain.Entities.Title", "Title")
                        .WithMany("KeywordTitles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_keyword_titles_titles_title_id");

                    b.Navigation("Keyword");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Watchly.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Season", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.Title", "Title")
                        .WithMany("Seasons")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seasons_titles_title_id");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.TitleGenre", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.Genre", "Genre")
                        .WithMany("TitleGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_title_genres_genres_genre_id");

                    b.HasOne("Watchly.Domain.Entities.Title", "Title")
                        .WithMany("TitleGenres")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_title_genres_titles_title_id");

                    b.Navigation("Genre");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.TitleProductionCompany", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.ProductionCompany", "ProductionCompany")
                        .WithMany("TitleProductionCompanies")
                        .HasForeignKey("ProductionCompanyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_title_production_companies_production_company_production_co~");

                    b.HasOne("Watchly.Domain.Entities.Title", "Title")
                        .WithMany("TitleProductionCompanies")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_title_production_companies_titles_title_id");

                    b.Navigation("ProductionCompany");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.TitleSpokenLanguage", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.SpokenLanguage", "SpokenLanguage")
                        .WithMany("TitleSpokenLanguages")
                        .HasForeignKey("SpokenLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_title_spoken_languages_spoken_languages_spoken_language_id");

                    b.HasOne("Watchly.Domain.Entities.Title", "Title")
                        .WithMany("TitleSpokenLanguages")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_title_spoken_languages_titles_title_id");

                    b.Navigation("SpokenLanguage");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.UserContentActivity", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.User", "User")
                        .WithMany("UserContentActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_content_activities_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.UserTitleProgress", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_user_title_progresses_titles_title_id");

                    b.HasOne("Watchly.Domain.Entities.User", "User")
                        .WithMany("UserTitleProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_user_title_progresses_asp_net_users_user_id");

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Vote", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.Episode", "Episode")
                        .WithMany("Votes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_votes_episodes_episode_id");

                    b.HasOne("Watchly.Domain.Entities.Title", "Title")
                        .WithMany("Votes")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_votes_titles_title_id");

                    b.HasOne("Watchly.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.WatchList", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.User", "User")
                        .WithMany("WatchLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watch_lists_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.WatchListItem", b =>
                {
                    b.HasOne("Watchly.Domain.Entities.Title", "Title")
                        .WithMany("WatchListItems")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watch_list_items_titles_title_id");

                    b.HasOne("Watchly.Domain.Entities.WatchList", "WatchList")
                        .WithMany("WatchListItems")
                        .HasForeignKey("WatchListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watch_list_items_watch_lists_watch_list_id");

                    b.Navigation("Title");

                    b.Navigation("WatchList");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Episode", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Genre", b =>
                {
                    b.Navigation("TitleGenres");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Keyword", b =>
                {
                    b.Navigation("KeywordTitles");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.ProductionCompany", b =>
                {
                    b.Navigation("TitleProductionCompanies");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.SpokenLanguage", b =>
                {
                    b.Navigation("TitleSpokenLanguages");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.Title", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("KeywordTitles");

                    b.Navigation("Seasons");

                    b.Navigation("TitleGenres");

                    b.Navigation("TitleProductionCompanies");

                    b.Navigation("TitleSpokenLanguages");

                    b.Navigation("Votes");

                    b.Navigation("WatchListItems");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserContentActivities");

                    b.Navigation("UserTitleProgresses");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("Watchly.Domain.Entities.WatchList", b =>
                {
                    b.Navigation("WatchListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
